### ISSUE TITLE
decryption is probably outdated, spits out random stuff

### ISSUE THREAD

**Issue by yorrd** [EloGank/lol-replay#2]
Heyo, this is an example of what `decrypt()` in ReplayCrypt.php spits out:

> ��DI��-G��M��:

I'm guessing this is due to the fact that the encryption method has changed. If you don't have the time or simply don't want to look into this, I'd appreciate an idea of where to start looking and how one figures out how it's encrypted.

Greetings

**Comment by Divi** [comment]
Hello,

I don't think the decryption method is outdated, but you may be right.  
By the way, the decrypted file in not readable by human. It's a plain text binary file. But you should be able to read some strings, like players name or "TURRET", somethings like that. So if you can read strings, the file is successfully decrypted :)

**Comment by yorrd** [comment]
Prompt response, here we go:

I have printed out everything I'm getting after decrypting, then searched for 'turret' but can't find anything. I'm aware this won't be very useful at all for the human eye, but I'm hoping I can reconstruct some stuff out of it.

Let me know if I can be of help in any way whatsoever, I'm really eager to get my hands on this. I'm just not sure about how to tackle the decryption issue...

**Comment by Divi** [comment]
Can you upload one of your keyframe please ? One decrypted version file and raw (encrypted) version file.

Thanks !

**Comment by yorrd** [comment]
[1.txt](https://github.com/EloGank/lol-replay/files/271487/1.txt)
[1.txt](https://github.com/EloGank/lol-replay/files/271488/1.txt)

first keyframe of a random game as the example script spit it out.

**Comment by Divi** [comment]
Thanks for the files but I forgot to ask you the game id & encryption key, sorry :(  
Can you give me this info ?

**Comment by yorrd** [comment]
[metas.json.txt](https://github.com/EloGank/lol-replay/files/271508/metas.json.txt)

That should do, right?

**Comment by Divi** [comment]
Indeed, thanks !

**Comment by Divi** [comment]
Hmm, it seems the decryption algo is outdated indeed.  
I'll try to find the new algo, but don't expect that I find the solution in the next few days :/

**Comment by yorrd** [comment]
@Divi 
Cool, thanks. I'll be looking forward to it! :+1:

**Comment by Divi** [comment]
I'm not sure it's even possible to find the new algo because decrypting keyframe/chunk is now forbidden by LoL Terms of Use since september 2014. We were a community of developers on the old algo and we had a lot of time. But for the new one, no one want to find it because parsing is not allowed anymore.

It appears that the decryption algo is outdated since 2015.
For now, I'll add a `deprecated` mention is the readme.

Feel free to reopen the issue if you find something.
